version: '3'
services:
  challenge-backend-magalu-api:
    container_name: challenge-backend-magalu-api
    build:
      context: .
    volumes:
      - ./:/opt/www
    ports:
      - 9501:9501
      - 9502:9502
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false
    stdin_open: true
    tty: true 
    restart: always

networks:
  default:
    name: challenge-backend-magalu-api
