services:
  challenge-backend-magalu-api:
    container_name: challenge-backend-magalu-api
    build:
      context: .
    volumes:
      - ./:/opt/www
    ports:
      - 9501:9501
      - 9502:9502
    networks:
      - challenge-backend-magalu-api
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false
    stdin_open: true
    tty: true 
    restart: always
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      #POSTGRES_DB: localstack
    ports:
      - 5432:5432
    networks:
      - challenge-backend-magalu-api
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - 5050:80
      - 5051:443
    networks:
      - challenge-backend-magalu-api
    depends_on:
      - postgres
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: kafka-zookeeper
    networks:
      - challenge-backend-magalu-api
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka-1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-1
    networks:
      - challenge-backend-magalu-api
    depends_on:
      - zookeeper
    ports:
      - 19092:19092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:19092
  kafka-2:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-2
    networks:
      - challenge-backend-magalu-api
    ports:
      - 29092:29092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:29092
  kafka-3:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-3
    networks:
      - challenge-backend-magalu-api
    ports:
      - 39092:39092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:39092
  kowl:
    image: quay.io/cloudhut/kowl:master
    container_name: kafka-kowl
    networks:
      - challenge-backend-magalu-api
    ports:
      - 8080:8080
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      KAFKA_BROKERS: kafka-1:19092,kafka-2:29092,kafka-3:39092

networks:
  challenge-backend-magalu-api:
    external: true
